apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: VirtualMachine
      version: v1
      group: kubevirt.io
      name: rhel10-gitops
    patch: |-
      - op: replace
        path: /spec/instancetype
        value: "u1.large"
