apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: VirtualMachine
      version: v1
      group: kubevirt.io
      name: rhel9-gitops
    patch: |-
      - op: replace
        path: /spec/template/spec/domain/cpu/sockets
        value: 8
