apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: demo-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: metrodrvm
        server: "{{server}}"
      project: default
      sources:
        - path: testmetrodr2
          repoURL: https://github.com/dieterdm/gitops-demo
          targetRevision: main
          repositoryType: git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo-placement
  namespace: openshift-gitops
  annotations:
    cluster.open-cluster-management.io/experimental-scheduling-disable: "true"
    drplacementcontrol.ramendr.openshift.io/drpc-name: demo-placement-drpc
    drplacementcontrol.ramendr.openshift.io/drpc-namespace: openshift-gitops
  finalizers:
    - drpc.ramendr.openshift.io/finalizer
spec:
  clusterSets:
    - disasterrecoverydemo
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - operator: In
              key: name
              values:
                - metrodr1
        claimSelector: {}
  decisionStrategy:
    groupStrategy:
      clustersPerDecisionGroup: 0
  prioritizerPolicy:
    mode: Additive
  spreadPolicy: {}
  numberOfClusters: 1
